spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: db.migration/v1_limit_table.sql

value:
  limit:
    dayLimit: 10000.00

server:
  port: 6556

scheduler:
  enabled: true